# Read documentation at https://async-aws.com/integration/symfony-bundle.html
async_aws:
    config:
        region: eu-central-1
        endpoint: http://localhost:4566
        pathStyleEndpoint: true

    # All installed clients are automatically autowired. Use this section to customize clients
    clients:
